### ISSUE TITLE
Typo on last line of build

### ISSUE THREAD

**Issue by pclerie** [antifob/lxd-windows#1]
diff --git a/Makefile b/Makefile
index 61e3c91..84a8335 100644
--- a/Makefile
+++ b/Makefile
@@ -43,7 +43,7 @@ BUILD=        build() { \
                        ./isos/virtio-win.iso \
                        ./local/ \
                        ./output/win$$1/; \
-               sh ./tools/mkmeta $$1 >./output/win/$$1/lxd.tar.xz; \
+               sh ./tools/mkmeta $$1 >./output/win$$1/lxd.tar.xz; \
        }; build

**Comment by pclerie** [comment]
Very useful stuff. Thanks.
:-D

Philippe

**Comment by antifob** [comment]
Thanks for the kind words! :)

Fixed in https://github.com/antifob/lxd-windows/commit/85d6bc29ccdb8702198962b8cd9cd4f1cae0dbbd
