### ISSUE TITLE
An explanation of the instructions would be appreciated

### ISSUE THREAD

**Issue by spiritLHLS** [antifob/lxd-windows#2]
```
# Build a disk image (disk.qcow2) and metadata archive (incus.tar.xz)
# in ./output/win2022/
make 2022
```

May I ask how disk.qcow2 and incus.tar.xz should be created here?
All I get after doing distrobuilder repack-windows is an .iso file.

**Comment by antifob** [comment]
Hey, this project is provided as is. If you can't bother to read the code, why would I read and explain it to you? :)

Regarding the distrobuilder line... okay. Feel free to use `distrobuilder` if that suits your need.

**Comment by spiritLHLS** [comment]
I see what you mean, just execute a command like make 2022 to get the appropriate file, I thought this was something that needed to be prepared in advance, but I didn't realize it was an explanation of the command to execute.
